name: Build and publish Armbian binary deb packages
on:
  push:
    branches:
      - main
    paths:
      - 'debian/changelog'
  workflow_dispatch: # allow manual triggering

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up build environment and artifacts directory
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts xz-utils apt-utils
          mkdir debian/artifacts
      - name: Build deb packages
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
      - name: Create distribution index files
        run: |
          dpkg-scanpackages -m debian/artifacts /dev/null | tee \
            >(gzip -9c > debian/artifacts/Packages.gz) \
            >(xz -9 > debian/artifacts/Packages.xz)
          apt-ftparchive release debian/artifacts > debian/artifacts/Release
      - name: Commit changes if any
        run: |
          git checkout data
          mkdir -p data
          mv ${{ github.workspace }}/debian/files data/
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/.
          git diff --cached --quiet || git commit -m "Update published repository files"
          git push
      - name: "publish repository to web server"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: "Generate directory"
