name: Build and publish Armbian binary deb packages
on:
  push:
    branches:
      - main
    paths:
      - 'debian/changelog'
  workflow_dispatch: # allow manual triggering

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up build environment and artifacts directory
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential reprepro
      - name: Build deb packages
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=full --no-sign
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_KEY1 }}
          passphrase: ${{ secrets.GPG_PASSPHRASE1 }}
      - name: Create distribution repository
        run: |
          reprepro -b debian/artifacts includedsc stable debian/artifacts/*.dsc
          reprepro -b debian/artifacts includedeb stable debian/artifacts/*.deb
          reprepro -b debian/artifacts export
      - name: Commit changes if any
        run: |
          git checkout data
          mkdir -p data
          cp -rf ${{ github.workspace }}/debian/artifacts/{pool,dists} data/
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/.
          git diff --cached --quiet || git commit -m "Update published repository files"
          git push
      - name: "publish repository to web server"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: "Generate directory"
