name: build Armbian binary deb packages
on:
  push:
    paths:
      - 'debian/changelog'
  workflow_dispatch: # allow manual triggering

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
      - name: Log files in artifacts directory
        run: ls -la debian/artifacts
      - name: Upload .deb artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-artifacts
          path: debian/artifacts/*.deb
